apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cm
            - secretRef:
                name: {{ .Release.Name }}-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  metadata:
    labels:
      app: {{ .Release.Name }}-backend
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
data:
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_HOST: postgresql.{{ .Release.Namespace }}
  DB_PORT: {{ .Values.postgresql.primary.service.port | default 5432 | quote }}
  TABLE_NAME: {{ .Values.backend.table_name | quote }}
  MINDSDB_URL: {{ .Values.backend.mindsdb_url | default (printf "http://%s-mindsdb.%s:47334" .Release.Name .Release.Namespace) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  API_KEY: {{ .Values.backend.api_key | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}